name: Continuos-Integration

on: push

jobs:
  linter:
    name: Lint Code with eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tests:
    runs-on: ubuntu-latest
    name: Test Code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Npm Install for CI environment
        run: npm ci
      - run: npm run build --if-present
      - run: npm test


    

  