name: Continuos-Integration


on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches-ignore: [ master ]

jobs:
  linter:
    name: Lint Code with eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Npm Install for CI environment
        run: npm ci --prefix backend
      - name: Run Eslint
        run: npm run lint --prefix backend
  tests:
    runs-on: ubuntu-latest
    name: Test Code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Npm Install for CI environment
        run: npm ci --prefix backend
      - run: npm run build --if-present --prefix backend
      - run: npm test --prefix backend


    

  