name: Continuos-Deployment

on:
  push:
    branches: [ master ]
jobs:
  linter:
    name: Lint Code with eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Npm Install for CI environment
        run: npm ci --prefix backend
      - name: Run Eslint
        run: npm run lint --prefix backend
  tests:
    runs-on: ubuntu-latest
    name: Test Code
    needs: linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Npm Install for CI environment
        run: npm ci --prefix backend
      - run: npm run build --if-present --prefix backend
      - run: npm test --prefix backend
  deploy:
    name: deploy in Heroku
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add remote origin
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Deploy backend to heroku
        run: git push --force heroku `git subtree split --prefix backend HEAD`:master

    

  